# Build Docker image for this app using Azure Pipelines

# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  imageName: 'nodejssample:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    npm install
    npm test
    docker build -f Dockerfile -t gurudocker23/$(imageName) .
    docker login -u gurudocker23 -p Waheguru@1
    docker push gurudocker23/$(imageName)
  env:
    pswd: Waheguru@1

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for JavaScript'

- task: CmdLine@2
  inputs:
    script: |
      echo "in coverage"
      cd coverage

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    

- task: SendEmail@1
  inputs:
    To: 'guruditsinghbarar1994@gmail.com'
    From: 'gurditsinghbrar1994@gmail.com'
    Subject: 'corbertura results'
    BodyAsHtml: true
    AddAttachment: true
    Attachment: '/home/vsts/work/_temp/cchtml/index.html'